"""Access to the bundled OpenSkiMap ski-area index and Liftie crosswalk.

Both files are gzipped JSON generated by ``scripts/build_ski_area_index.py``
from OpenSkiMap's daily GeoJSON (ODbL) and Liftie's resort coordinates (BSD).
They are loaded once, lazily, and cached for the process.

* ``ski_area_index.json.gz`` — list of distilled ski-area records (id, name,
  country/region, coordinates, lift/run terrain statistics, website, wikidata).
* ``liftie_crosswalk.json.gz`` — ``{liftie_slug: {"id": openskimap_id, ...}}``;
  inverted here to map an OpenSkiMap id to its Liftie slug.
"""

from __future__ import annotations

import gzip
import json
from functools import lru_cache
from pathlib import Path
from typing import Any

_DATA_DIR = Path(__file__).parent / "data"
_INDEX_FILE = _DATA_DIR / "ski_area_index.json.gz"
_CROSSWALK_FILE = _DATA_DIR / "liftie_crosswalk.json.gz"


@lru_cache(maxsize=1)
def _load_index() -> list[dict[str, Any]]:
    with gzip.open(_INDEX_FILE, "rt", encoding="utf-8") as handle:
        return json.load(handle)


@lru_cache(maxsize=1)
def _id_to_slug() -> dict[str, str]:
    """Invert the Liftie crosswalk to map OpenSkiMap id -> Liftie slug."""
    with gzip.open(_CROSSWALK_FILE, "rt", encoding="utf-8") as handle:
        crosswalk: dict[str, dict[str, Any]] = json.load(handle)
    mapping: dict[str, str] = {}
    for slug, entry in crosswalk.items():
        area_id = entry.get("id")
        # First slug wins if several map to one area (sub-areas of a megaresort).
        if area_id and area_id not in mapping:
            mapping[area_id] = slug
    return mapping


def _normalize(text: str) -> str:
    return "".join(ch for ch in text.lower() if ch.isalnum())


def search_areas(
    query: str, country: str | None = None, limit: int = 25
) -> list[dict[str, Any]]:
    """Return ski-area records matching a name query (and optional country).

    Case/space/punctuation-insensitive substring match on the name; results are
    ranked with prefix matches first, then by lift count (bigger resorts up).
    """
    q = _normalize(query)
    results: list[tuple[int, int, dict[str, Any]]] = []
    for area in _load_index():
        if country and area.get("country") != country:
            continue
        name = _normalize(area.get("name") or "")
        if q and q not in name:
            continue
        # Rank: 0 = prefix match, 1 = substring; then by -lift count.
        rank = 0 if name.startswith(q) else 1
        results.append((rank, -(area.get("lifts") or 0), area))
    results.sort(key=lambda item: (item[0], item[1]))
    return [area for _, _, area in results[:limit]]


def get_area(area_id: str) -> dict[str, Any] | None:
    """Return the bundled record for an OpenSkiMap id, or ``None``."""
    for area in _load_index():
        if area.get("id") == area_id:
            return area
    return None


def countries() -> list[str]:
    """Sorted list of distinct countries present in the index."""
    return sorted({a["country"] for a in _load_index() if a.get("country")})


def liftie_slug_for(area_id: str) -> str | None:
    """Best-guess Liftie/skiapi slug for an OpenSkiMap id, or ``None``."""
    return _id_to_slug().get(area_id)
